from sqlalchemy import Column, Integer, String, Boolean, DateTime, Enum as SQLEnum, Float, Text, ForeignKey, Date
from sqlalchemy.orm import relationship
from datetime import datetime, date
import enum
from app.db.database import Base


class MRPRunStatus(str, enum.Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETE = "complete"
    ERROR = "error"


class PlanningAction(str, enum.Enum):
    ORDER = "order"  # Create purchase order
    MANUFACTURE = "manufacture"  # Create work order
    RESCHEDULE_IN = "reschedule_in"  # Move date earlier
    RESCHEDULE_OUT = "reschedule_out"  # Move date later
    CANCEL = "cancel"  # Cancel existing order
    EXPEDITE = "expedite"  # Rush order needed


class MRPRun(Base):
    """MRP Run - snapshot of material planning calculation"""
    __tablename__ = "mrp_runs"
    
    id = Column(Integer, primary_key=True, index=True)
    run_number = Column(String(50), unique=True, index=True, nullable=False)
    
    # Run parameters
    planning_horizon_days = Column(Integer, default=90)
    include_safety_stock = Column(Boolean, default=True)
    include_allocated = Column(Boolean, default=True)
    
    # Status
    status = Column(SQLEnum(MRPRunStatus), default=MRPRunStatus.PENDING)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    error_message = Column(Text, nullable=True)
    
    # Summary stats
    total_parts_analyzed = Column(Integer, default=0)
    total_requirements = Column(Integer, default=0)
    total_actions = Column(Integer, default=0)
    
    # Audit
    created_at = Column(DateTime, default=datetime.utcnow)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    # Relationships
    requirements = relationship("MRPRequirement", back_populates="mrp_run", cascade="all, delete-orphan")
    actions = relationship("MRPAction", back_populates="mrp_run", cascade="all, delete-orphan")


class MRPRequirement(Base):
    """Material requirements generated by MRP"""
    __tablename__ = "mrp_requirements"
    
    id = Column(Integer, primary_key=True, index=True)
    mrp_run_id = Column(Integer, ForeignKey("mrp_runs.id"), nullable=False)
    part_id = Column(Integer, ForeignKey("parts.id"), nullable=False)
    
    # Requirement details
    required_date = Column(Date, nullable=False)
    quantity_required = Column(Float, nullable=False)
    quantity_on_hand = Column(Float, default=0.0)
    quantity_on_order = Column(Float, default=0.0)  # Open POs
    quantity_allocated = Column(Float, default=0.0)  # Reserved for WOs
    quantity_available = Column(Float, default=0.0)  # on_hand - allocated
    quantity_shortage = Column(Float, default=0.0)  # Required - available - on_order
    
    # Source of requirement
    source_type = Column(String(50))  # work_order, sales_order, safety_stock, forecast
    source_id = Column(Integer, nullable=True)
    source_number = Column(String(100))
    
    # Parent in BOM explosion
    parent_part_id = Column(Integer, ForeignKey("parts.id"), nullable=True)
    bom_level = Column(Integer, default=0)
    
    # Relationships
    mrp_run = relationship("MRPRun", back_populates="requirements")
    part = relationship("Part", foreign_keys=[part_id])
    parent_part = relationship("Part", foreign_keys=[parent_part_id])


class MRPAction(Base):
    """Recommended actions from MRP"""
    __tablename__ = "mrp_actions"
    
    id = Column(Integer, primary_key=True, index=True)
    mrp_run_id = Column(Integer, ForeignKey("mrp_runs.id"), nullable=False)
    part_id = Column(Integer, ForeignKey("parts.id"), nullable=False)
    
    # Action details
    action_type = Column(SQLEnum(PlanningAction), nullable=False)
    priority = Column(Integer, default=5)  # 1=highest
    
    # Quantities
    quantity = Column(Float, nullable=False)
    
    # Dates
    required_date = Column(Date, nullable=False)
    suggested_order_date = Column(Date, nullable=False)  # Required - lead time
    
    # For reschedule actions
    current_date = Column(Date, nullable=True)
    reference_type = Column(String(50), nullable=True)  # work_order, purchase_order
    reference_id = Column(Integer, nullable=True)
    reference_number = Column(String(100), nullable=True)
    
    # Status
    processed = Column(Boolean, default=False)
    processed_at = Column(DateTime, nullable=True)
    processed_by = Column(Integer, nullable=True)
    result_wo_id = Column(Integer, ForeignKey("work_orders.id"), nullable=True)
    result_po_id = Column(Integer, ForeignKey("purchase_orders.id"), nullable=True)
    error_message = Column(Text, nullable=True)

    # Notes
    notes = Column(Text)
    
    # Relationships
    mrp_run = relationship("MRPRun", back_populates="actions")
    part = relationship("Part")
