import React, { useState } from 'react';
import { fabricationQuoteApi } from './api';
import { AddButton, Card, DecimalField, Empty, IntegerField, PartField, Section, TextField, Toggle } from './components';
import { money, readableError } from './model';
import { objectValue } from './SourcesPanel';
import { newEvidence, newId } from './types';
import type { QuoteFile, QuotePlan } from './types';

interface Blank { id: string; quantity: number; material: string; thickness_mm: string | null; width_mm: string | null; height_mm: string | null; rotate: boolean }
interface Stock { id: string; quantity: number; material: string; thickness_mm: string | null; width_mm: string | null; height_mm: string | null; price: string | null }
interface Props { plan: QuotePlan; files: QuoteFile[]; onChange: (plan: QuotePlan) => void; onSave: (input: unknown) => Promise<void>; canSave: boolean; editable: boolean; busy: boolean }
export function NestingPanel({ plan, files, onChange, onSave, canSave, editable, busy }: Props) {
  const [blanks, setBlanks] = useState<Blank[]>([]); const [stocks, setStocks] = useState<Stock[]>([]);
  const [spacing, setSpacing] = useState<string | null>(null); const [margin, setMargin] = useState<string | null>(null);
  const [result, setResult] = useState<Record<string, unknown> | null>(null); const [previewInput, setPreviewInput] = useState<unknown>(null);
  const [working, setWorking] = useState(false); const [error, setError] = useState(''); const [owner, setOwner] = useState(plan.roots[0]?.part_id || '');
  const parseDimension = (value: string | null, positive = true) => { if (value === null || !/^\d+(?:\.\d+)?$/.test(value) || !Number.isFinite(Number(value)) || (positive ? Number(value) <= 0 : Number(value) < 0)) throw new Error('Enter valid dimensions, thickness, spacing and margins. Unknown values cannot define a nest.'); return Number(value); };
  const buildInput = () => {
    if (!blanks.length || !stocks.length) throw new Error('Add at least one blank and one stock sheet.');
    if (blanks.some(b => !b.id || !b.material.trim() || !Number.isInteger(b.quantity) || b.quantity < 1) || stocks.some(s => !s.material.trim() || !Number.isInteger(s.quantity) || s.quantity < 1)) throw new Error('Specify a part, exact material identity and positive whole quantities for every blank and stock.');
    if (new Set(blanks.map(b => b.id)).size !== blanks.length) throw new Error('Combine repeated blank definitions into one quantity before nesting.');
    return { parts: blanks.map(b => ({ id: b.id, quantity: b.quantity, material: b.material, thickness_mm: parseDimension(b.thickness_mm), width_mm: parseDimension(b.width_mm), height_mm: parseDimension(b.height_mm), allowed_rotations: b.rotate ? [0, 90] : [0] })), stocks: stocks.map(s => ({ ...s, thickness_mm: parseDimension(s.thickness_mm), width_mm: parseDimension(s.width_mm), height_mm: parseDimension(s.height_mm), price: s.price, currency: plan.currency })), spacing_mm: parseDimension(spacing, false), edge_margin_mm: parseDimension(margin, false) };
  };
  const preview = async () => { if (working) return; setError(''); try { const input = buildInput(); setWorking(true); setResult(await fabricationQuoteApi.nest(input)); setPreviewInput(input); } catch (e) { setError(readableError(e)); } finally { setWorking(false); } };
  let current = false; try { current = previewInput !== null && JSON.stringify(buildInput()) === JSON.stringify(previewInput); } catch { /* Transient inputs deliberately invalidate the preview. */ }
  const nestFiles = files.filter(f => objectValue(f.analysis).kind === 'nest' || objectValue(f.analysis).nest_input != null || f.kind === 'nest');
  const apply = (file: QuoteFile) => {
    const nest = objectValue(objectValue(file.analysis).geometry); const prices = objectValue(nest.cost_by_currency);
    const root = plan.roots.find(r => r.part_id === owner); const source = `nest:${file.id}`;
    if (!root || !nest.fully_priced || nest.status !== 'complete' || prices[plan.currency] == null || plan.materials.some(m => m.evidence.source === source)) return;
    onChange({ ...plan, materials: [...plan.materials, { id: newId('material'), part_id: owner, description: `Nested stock · ${file.file_name}`, quantity_basis: 'per_batch', batch_size: root.quantity, consumed_quantity: '1', unit: 'each', unit_cost: String(prices[plan.currency]), evidence: { ...newEvidence(), source, note: `One complete stock allocation for the saved nest, ${String(nest.sheet_count)} sheet(s); owner demand ${root.quantity}. Review stock price, quantities, spacing and orientation.` } }] });
  };
  return <Section title="Internal material nesting" description="Plan conservative rectangular blanks against available stock. Confirm dimensions and allowed rotation; machine connections are not required.">
    <fieldset disabled={!editable || busy || working}>
      <div className="fq-subheading"><h3>Reviewed blank envelopes</h3><AddButton disabled={!plan.parts.length} onClick={() => setBlanks([...blanks, { id: plan.parts[0].id, quantity: 1, material: '', thickness_mm: null, width_mm: null, height_mm: null, rotate: false }])}>Add blank</AddButton></div>
      {!blanks.length && <Empty>Add the required quantity of every sheet component. Width and height must describe a reviewed flat blank.</Empty>}
      {blanks.map((blank, i) => <Card key={i} title={`Blank ${i + 1}`} onRemove={() => setBlanks(blanks.filter((_, j) => i !== j))}><div className="fq-grid fq-grid-3"><PartField parts={plan.parts} value={blank.id} onChange={id => setBlanks(blanks.map((b, j) => i === j ? { ...b, id } : b))} /><TextField label="Exact material identity" value={blank.material} onChange={material => setBlanks(blanks.map((b, j) => i === j ? { ...b, material } : b))} /><IntegerField label="Blank quantity" value={blank.quantity} onChange={quantity => setBlanks(blanks.map((b, j) => i === j ? { ...b, quantity } : b))} />{(['thickness_mm', 'width_mm', 'height_mm'] as const).map(key => <DecimalField key={key} label={`${key.split('_')[0]} (mm)`} value={blank[key]} onChange={value => setBlanks(blanks.map((b, j) => i === j ? { ...b, [key]: value } : b))} />)}</div><Toggle label="90° rotation is allowed by grain and finish requirements" checked={blank.rotate} onChange={rotate => setBlanks(blanks.map((b, j) => i === j ? { ...b, rotate } : b))} /></Card>)}
      <div className="fq-subheading"><h3>Stock sheet options</h3><AddButton onClick={() => setStocks([...stocks, { id: newId('stock'), quantity: 1, material: '', thickness_mm: null, width_mm: null, height_mm: null, price: null }])}>Add stock</AddButton></div>
      {stocks.map((stock, i) => <Card key={stock.id} title={`Stock ${i + 1}`} onRemove={() => setStocks(stocks.filter((_, j) => i !== j))}><div className="fq-grid fq-grid-3"><TextField label="Stock material identity" value={stock.material} onChange={material => setStocks(stocks.map((s, j) => i === j ? { ...s, material } : s))} /><IntegerField label="Available sheets" value={stock.quantity} onChange={quantity => setStocks(stocks.map((s, j) => i === j ? { ...s, quantity } : s))} /><DecimalField label={`Purchased price / sheet (${plan.currency})`} value={stock.price} onChange={price => setStocks(stocks.map((s, j) => i === j ? { ...s, price } : s))} />{(['thickness_mm', 'width_mm', 'height_mm'] as const).map(key => <DecimalField key={key} label={`Stock ${key.split('_')[0]} (mm)`} value={stock[key]} onChange={value => setStocks(stocks.map((s, j) => i === j ? { ...s, [key]: value } : s))} />)}</div></Card>)}
      <div className="fq-row"><DecimalField label="Part spacing (mm)" value={spacing} onChange={setSpacing} /><DecimalField label="Sheet edge margin (mm)" value={margin} onChange={setMargin} /><button type="button" className="fq-btn fq-btn-primary" onClick={() => void preview()}>Calculate nest</button></div>
    </fieldset>
    {error && <div className="fq-alert" role="alert">{error}</div>}{working && <p role="status">Calculating stock layout…</p>}
    {result && <><NestResult result={result} input={previewInput} />{!current && <p className="fq-alert">Nest inputs changed. Recalculate before saving.</p>}<button type="button" className="fq-btn fq-btn-secondary" disabled={!canSave || !editable || busy || !current || result.status !== 'complete'} onClick={() => void onSave(previewInput)}>Save nest evidence</button><p className="fq-hint">Save the current quote first. A saved nest is retained with its exact input, layout and stock cost.</p></>}
    {nestFiles.length > 0 && <div className="fq-saved-nests"><h3>Saved nest evidence</h3><PartField label="Charge stock once to this root assembly" parts={plan.parts.filter(p => plan.roots.some(r => r.part_id === p.id))} value={owner} onChange={setOwner} />{nestFiles.map(file => { const nest = objectValue(objectValue(file.analysis).geometry); const applied = plan.materials.some(m => m.evidence.source === `nest:${file.id}`); return <Card key={file.id} title={file.file_name}><NestResult result={nest} input={objectValue(file.analysis).nest_input} /><button type="button" className="fq-btn fq-btn-secondary" disabled={!editable || busy || applied || !owner || !nest.fully_priced || nest.status !== 'complete'} onClick={() => apply(file)}>{applied ? 'Material allocation added' : 'Apply one batch of stock cost'}</button><p className="fq-hint">Review the resulting material line and this source file. Changes to required quantities invalidate the saved layout.</p></Card>; })}</div>}
  </Section>;
}

function NestResult({ result, input }: { result: Record<string, unknown>; input?: unknown }) {
  const placements = Array.isArray(result.placements) ? result.placements.map(objectValue) : [];
  const sheets = Array.isArray(result.sheets_used) ? result.sheets_used.map(objectValue) : [];
  const stockInput = objectValue(input); const stocks = (Array.isArray(stockInput.stocks) ? stockInput.stocks : []).map(objectValue);
  return <div className="fq-nest-result"><div className="fq-review-meta"><span className={`fq-pill ${result.status === 'complete' ? 'fq-pill-green' : 'fq-pill-amber'}`}>{String(result.status || 'Unknown')}</span><span>{String(result.sheet_count ?? 0)} sheets</span><span>Feasible layout · optimality not proven</span></div><div className="fq-nest-sheets">{sheets.map((sheet, i) => { const parts = placements.filter(p => p.stock_id === sheet.stock_id && p.stock_instance === sheet.stock_instance); const bounds = parts.map(p => p.envelope_mm).filter(Array.isArray) as number[][]; const stock = stocks.find(s => s.id === sheet.stock_id); const width = Number(stock?.width_mm) || Math.max(1, ...bounds.map(b => Number(b[2]))); const height = Number(stock?.height_mm) || Math.max(1, ...bounds.map(b => Number(b[3]))); return <figure key={i}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Nest sheet ${i + 1}, ${parts.length} placements`}><rect width={width} height={height} fill="var(--fd-sunken)" stroke="var(--fd-line-bright)" strokeWidth={Math.max(width, height) / 250} />{parts.map((p, j) => { const outline = p.outline_mm as number[][]; return Array.isArray(outline) ? <polygon key={j} points={outline.map(point => point.join(',')).join(' ')} fill={['var(--fd-blue)', 'var(--fd-cyan)', 'var(--fd-link)', 'var(--fd-mute)'][j % 4]} fillOpacity={0.65} stroke="var(--fd-sunken)" strokeWidth={Math.max(width, height) / 400}><title>{String(p.part_id)} #{String(p.part_instance)}</title></polygon> : null; })}</svg><figcaption>Sheet {i + 1} · {parts.length} parts</figcaption></figure>; })}</div>{Object.entries(objectValue(result.cost_by_currency)).map(([currency, cost]) => <p key={currency}><strong>Stock cash: {money(cost, currency)}</strong></p>)}{Array.isArray(result.unplaced) && result.unplaced.length > 0 && <div className="fq-alert">{result.unplaced.map((item, i) => <p key={i}>{String(objectValue(item).quantity)} × {String(objectValue(item).part_id)}: {String(objectValue(item).reason)}</p>)}</div>}<details className="fq-details"><summary>Nest validation evidence</summary><pre className="fq-json">{JSON.stringify(result, null, 2)}</pre></details></div>;
}
