import React from 'react';
import { AddButton, Card, DecimalField, Empty, EvidenceEditor, IntegerField, PartField, RemoveButton, Section, SelectField, TextField, Toggle } from './components';
import { currencies, newEvidence, newId, newRecipe } from './types';
import type { Evidence, HardwareLine, OperationLine, QuotePlan, Recipe, SupplierOffer } from './types';
import { ProcessProfilesPanel } from './ProcessProfilesPanel';

interface Props { plan: QuotePlan; onChange: (plan: QuotePlan) => void }
const changed = <T extends { evidence: Evidence }>(row: T, patch: Partial<T>): T => ({ ...row, ...patch, evidence: patch.evidence ?? { ...row.evidence, reviewed: false } });
const replace = <T,>(rows: T[], index: number, value: T): T[] => rows.map((row, i) => i === index ? value : row);
const without = <T,>(rows: T[], index: number): T[] => rows.filter((_, i) => i !== index);

export function AssemblyEditor({ plan, onChange }: Props) {
  return <>
    <Section title="Part definitions" description="Define each unique component once. Assembly occurrences and quantities are added below." action={<AddButton onClick={() => onChange({ ...plan, parts: [...plan.parts, { id: newId('part'), name: '', make_or_buy: 'make', costing_complete: false, purchase_unit_cost: null, evidence: newEvidence() }] })}>Add part</AddButton>}>
      {!plan.parts.length && <Empty>Add the top-level assembly and its make or buy components to begin.</Empty>}
      {plan.parts.map((part, index) => <Card key={part.id} title={part.name || 'Untitled part'} index={index} onRemove={() => onChange({ ...plan, parts: without(plan.parts, index) })}>
        <div className="fq-grid fq-grid-3"><TextField label="Part number / description" value={part.name} onChange={name => onChange({ ...plan, parts: replace(plan.parts, index, changed(part, { name })) })} /><SelectField label="Make or buy" value={part.make_or_buy} onChange={make_or_buy => onChange({ ...plan, parts: replace(plan.parts, index, changed(part, { make_or_buy })) })} options={['make', 'buy']} />{part.make_or_buy === 'buy' && <DecimalField label={`Purchase cost / unit (${plan.currency})`} value={part.purchase_unit_cost} onChange={purchase_unit_cost => onChange({ ...plan, parts: replace(plan.parts, index, changed(part, { purchase_unit_cost })) })} />}</div>
        <Toggle label="All required material and work for this part are represented" checked={part.costing_complete} onChange={costing_complete => onChange({ ...plan, parts: replace(plan.parts, index, changed(part, { costing_complete })) })} hint="Confirm after reviewing the full drawing, BOM and process route." />
        <EvidenceEditor value={part.evidence} onChange={evidence => onChange({ ...plan, parts: replace(plan.parts, index, { ...part, evidence }) })} />
      </Card>)}
    </Section>
    <Section title="Quoted demand" description="How many top-level assemblies or standalone parts is the customer requesting?" action={<AddButton disabled={!plan.parts.length} onClick={() => onChange({ ...plan, roots: [...plan.roots, { part_id: plan.parts[0].id, quantity: '1' }] })}>Add demand</AddButton>}>
      {!plan.roots.length && <Empty>No quantity specified yet.</Empty>}
      {plan.roots.map((root, i) => <div className="fq-row" key={i}><PartField parts={plan.parts} value={root.part_id} onChange={part_id => onChange({ ...plan, roots: replace(plan.roots, i, { ...root, part_id }) })} /><DecimalField label="Customer quantity" value={root.quantity} onChange={quantity => onChange({ ...plan, roots: replace(plan.roots, i, { ...root, quantity: quantity ?? '' }) })} /><RemoveButton label={`Remove demand ${i + 1}`} onClick={() => onChange({ ...plan, roots: without(plan.roots, i) })} /></div>)}
    </Section>
    <Section title="Assembly BOM" description="Each row is a parent-to-component relationship. Quantities multiply through every level." action={<AddButton disabled={plan.parts.length < 2} onClick={() => onChange({ ...plan, bom: [...plan.bom, { id: newId('bom'), parent_id: plan.parts[0].id, child_id: plan.parts[1].id, quantity: '1' }] })}>Add component</AddButton>}>
      {!plan.bom.length && <Empty>No assembly relationships. Standalone parts can be quoted directly.</Empty>}
      {plan.bom.map((edge, i) => <div className="fq-row" key={edge.id}><PartField label="Parent assembly" parts={plan.parts} value={edge.parent_id} onChange={parent_id => onChange({ ...plan, bom: replace(plan.bom, i, { ...edge, parent_id }) })} /><PartField label="Child component" parts={plan.parts} value={edge.child_id} onChange={child_id => onChange({ ...plan, bom: replace(plan.bom, i, { ...edge, child_id }) })} /><DecimalField label="Quantity per parent" value={edge.quantity} onChange={quantity => onChange({ ...plan, bom: replace(plan.bom, i, { ...edge, quantity: quantity ?? '' }) })} /><RemoveButton label={`Remove BOM component ${i + 1}`} onClick={() => onChange({ ...plan, bom: without(plan.bom, i) })} /></div>)}
      <p className="fq-hint">Deleting a definition keeps its references visible as unresolved; the calculation checks missing parts and cyclic assemblies.</p>
    </Section>
  </>;
}

export function MaterialsEditor({ plan, onChange }: Props) {
  return <Section title="Material allocation" description="Enter purchased material allocated to each part or batch. Keep this separate from net part weight." action={<AddButton disabled={!plan.parts.length} onClick={() => onChange({ ...plan, materials: [...plan.materials, { id: newId('material'), part_id: plan.parts[0].id, description: '', quantity_basis: 'per_unit', batch_size: '1', consumed_quantity: null, unit: 'kg', unit_cost: null, evidence: newEvidence() }] })}>Add material</AddButton>}>
    {!plan.materials.length && <Empty>Add stock, sheet or weight allocations and a dated price source.</Empty>}
    {plan.materials.map((line, index) => {
      const patch = (value: Partial<typeof line>) => onChange({ ...plan, materials: replace(plan.materials, index, changed(line, value)) });
      return <Card key={line.id} title={line.description || 'Material allocation'} index={index} onRemove={() => onChange({ ...plan, materials: without(plan.materials, index) })}><div className="fq-grid fq-grid-3">
        <PartField parts={plan.parts} value={line.part_id} onChange={part_id => patch({ part_id })} /><TextField label="Material / grade / thickness" value={line.description} onChange={description => patch({ description })} /><SelectField label="Allocation basis" value={line.quantity_basis} onChange={quantity_basis => patch({ quantity_basis })} options={['per_unit', 'per_batch']} />
        {line.quantity_basis === 'per_batch' && <DecimalField label="Parts per batch" value={line.batch_size} onChange={batch_size => patch({ batch_size: batch_size ?? '' })} />}
        <DecimalField label="Consumed material quantity" value={line.consumed_quantity} onChange={consumed_quantity => patch({ consumed_quantity })} /><SelectField label="Material unit" value={line.unit} onChange={unit => patch({ unit })} options={['kg', 'lb', 'mm2', 'm2', 'ft2', 'sheet', 'each']} /><DecimalField label={`Cost / material unit (${plan.currency})`} value={line.unit_cost} onChange={unit_cost => patch({ unit_cost })} />
      </div><EvidenceEditor value={line.evidence} onChange={evidence => patch({ evidence })} /></Card>;
    })}
  </Section>;
}

function RecipeEditor({ recipe, onChange }: { recipe: Recipe; onChange: (value: Recipe) => void }) {
  if (recipe.kind === 'manual') return <div className="fq-grid fq-grid-2"><DecimalField label="Run labor (person-seconds)" value={recipe.labor_seconds} onChange={labor_seconds => onChange({ ...recipe, labor_seconds })} /><DecimalField label="Run machine occupancy (seconds)" value={recipe.machine_seconds} onChange={machine_seconds => onChange({ ...recipe, machine_seconds })} /></div>;
  if (recipe.kind === 'laser') return <>
    <div className="fq-subheading"><h4>Cutting classes</h4><AddButton onClick={() => onChange({ ...recipe, cuts: [...recipe.cuts, { cut_length_mm: '', speed_mm_per_second: null, pierces: NaN, pierce_seconds: null }] })}>Add cut class</AddButton></div>
    {!recipe.cuts.length && <Empty>Add contour length and pierces for each material/quality cutting class.</Empty>}
    {recipe.cuts.map((cut, i) => <div className="fq-row fq-cut-row" key={i}><DecimalField label="Cut length (mm)" value={cut.cut_length_mm} onChange={cut_length_mm => onChange({ ...recipe, cuts: replace(recipe.cuts, i, { ...cut, cut_length_mm: cut_length_mm ?? '' }) })} /><DecimalField label="Effective speed (mm/s)" value={cut.speed_mm_per_second} onChange={speed_mm_per_second => onChange({ ...recipe, cuts: replace(recipe.cuts, i, { ...cut, speed_mm_per_second }) })} /><IntegerField label="Pierce count" value={cut.pierces} onChange={pierces => onChange({ ...recipe, cuts: replace(recipe.cuts, i, { ...cut, pierces }) })} /><DecimalField label="Seconds per pierce" value={cut.pierce_seconds} onChange={pierce_seconds => onChange({ ...recipe, cuts: replace(recipe.cuts, i, { ...cut, pierce_seconds }) })} /><RemoveButton label={`Remove cut class ${i + 1}`} onClick={() => onChange({ ...recipe, cuts: without(recipe.cuts, i) })} /></div>)}
    <div className="fq-grid fq-grid-3"><DecimalField label="Noncut machine time (s)" value={recipe.noncut_machine_seconds} onChange={noncut_machine_seconds => onChange({ ...recipe, noncut_machine_seconds })} /><DecimalField label="Run labor (person-seconds)" value={recipe.labor_seconds} onChange={labor_seconds => onChange({ ...recipe, labor_seconds })} /><DecimalField label="Dynamics allowance (s)" value={recipe.dynamics_allowance_seconds} onChange={dynamics_allowance_seconds => onChange({ ...recipe, dynamics_allowance_seconds })} /></div><Toggle label="Effective speeds include acceleration and cornering" checked={recipe.speed_includes_dynamics} onChange={speed_includes_dynamics => onChange({ ...recipe, speed_includes_dynamics })} hint="Otherwise provide a reviewed dynamics allowance. Straight-line top speed is insufficient." />
  </>;
  if (recipe.kind === 'brake') return <><div className="fq-grid fq-grid-3"><IntegerField label="Bend hits per run" value={recipe.hits} onChange={hits => onChange({ ...recipe, hits })} /><DecimalField label="Seconds per hit" value={recipe.seconds_per_hit} onChange={seconds_per_hit => onChange({ ...recipe, seconds_per_hit })} /><IntegerField label="Crew size" value={recipe.crew_size} onChange={crew_size => onChange({ ...recipe, crew_size })} /><DecimalField label="Handling time (s)" value={recipe.handling_seconds} onChange={handling_seconds => onChange({ ...recipe, handling_seconds })} /><DecimalField label="Inspection time (s)" value={recipe.inspection_seconds} onChange={inspection_seconds => onChange({ ...recipe, inspection_seconds })} /><DecimalField label="Machine occupancy (s)" value={recipe.machine_seconds} onChange={machine_seconds => onChange({ ...recipe, machine_seconds })} /></div><Toggle label="Tooling, tonnage, access and bend sequence reviewed" checked={recipe.feasibility_reviewed} onChange={feasibility_reviewed => onChange({ ...recipe, feasibility_reviewed })} /></>;
  return <div className="fq-grid fq-grid-3"><SelectField label="Welding process" value={recipe.process} onChange={process => onChange({ ...recipe, process })} options={['MIG', 'TIG', 'fiber_laser']} /><TextField label="Procedure / joint reference" value={recipe.procedure_reference} onChange={procedure_reference => onChange({ ...recipe, procedure_reference: procedure_reference || null })} /><IntegerField label="Weld crew size" value={recipe.crew_size} onChange={crew_size => onChange({ ...recipe, crew_size })} /><DecimalField label="Total weld travel length (mm)" value={recipe.weld_length_mm} onChange={weld_length_mm => onChange({ ...recipe, weld_length_mm })} hint="Account for all required passes and sides in the documented takeoff." /><DecimalField label="Specified weld size (mm)" value={recipe.weld_size_mm} onChange={weld_size_mm => onChange({ ...recipe, weld_size_mm })} /><DecimalField label="Travel speed (mm/s)" value={recipe.travel_speed_mm_per_second} onChange={travel_speed_mm_per_second => onChange({ ...recipe, travel_speed_mm_per_second })} /><DecimalField label="Nonweld attended seconds / crew member" value={recipe.nonweld_labor_seconds} onChange={nonweld_labor_seconds => onChange({ ...recipe, nonweld_labor_seconds })} /><DecimalField label="Nonweld machine time (s)" value={recipe.nonweld_machine_seconds} onChange={nonweld_machine_seconds => onChange({ ...recipe, nonweld_machine_seconds })} /></div>;
}

export function OperationsEditor({ plan, onChange }: Props) {
  const add = () => onChange({ ...plan, operations: [...plan.operations, { id: newId('op'), part_id: plan.parts[0].id, name: '', process: 'manual', setup_basis: 'per_quote', run_basis: 'per_unit', batch_size: '1', setup_labor_seconds: null, setup_machine_seconds: null, labor_rate_per_hour: null, machine_rate_per_hour: null, consumables_cost_per_run: null, outside_cost_per_run: null, recipe: newRecipe('manual'), evidence: newEvidence() }] });
  return <Section title="Process route" description="Model each operation's setup, run time and resources. Blank values mean unknown; enter zero only when confirmed." action={<AddButton disabled={!plan.parts.length} onClick={add}>Add operation</AddButton>}>
    <ProcessProfilesPanel plan={plan} onChange={onChange} />
    {!plan.operations.length && <Empty>Add laser, brake, welding or manual operations, including finishing and inspection where required.</Empty>}
    {plan.operations.map((line, index) => {
      const patch = (value: Partial<OperationLine>) => onChange({ ...plan, operations: replace(plan.operations, index, changed(line, value)) });
      return <Card key={line.id} title={line.name || 'New operation'} index={index} onRemove={() => onChange({ ...plan, operations: without(plan.operations, index) })}><div className="fq-grid fq-grid-3"><PartField parts={plan.parts} value={line.part_id} onChange={part_id => patch({ part_id })} /><TextField label="Operation / work center" value={line.name} onChange={name => patch({ name })} /><SelectField label="Calculation recipe" value={line.recipe.kind} onChange={kind => patch({ recipe: newRecipe(kind), process: kind })} options={['manual', 'laser', 'brake', 'weld']} /><SelectField label="Setup charged" value={line.setup_basis} onChange={setup_basis => patch({ setup_basis })} options={['per_quote', 'per_batch']} /><SelectField label="Run quantity basis" value={line.run_basis} onChange={run_basis => patch({ run_basis })} options={['per_unit', 'per_batch']} /><DecimalField label="Parts per batch" value={line.batch_size} onChange={batch_size => patch({ batch_size: batch_size ?? '' })} /></div>
        <h4 className="fq-form-heading">Setup & resource rates</h4><div className="fq-grid fq-grid-3"><DecimalField label="Setup labor (person-seconds)" value={line.setup_labor_seconds} onChange={setup_labor_seconds => patch({ setup_labor_seconds })} /><DecimalField label="Setup machine occupancy (s)" value={line.setup_machine_seconds} onChange={setup_machine_seconds => patch({ setup_machine_seconds })} /><DecimalField label={`Labor rate / hour (${plan.currency})`} value={line.labor_rate_per_hour} onChange={labor_rate_per_hour => patch({ labor_rate_per_hour })} /><DecimalField label={`Machine rate / hour (${plan.currency})`} value={line.machine_rate_per_hour} onChange={machine_rate_per_hour => patch({ machine_rate_per_hour })} /><DecimalField label={`Consumables / run (${plan.currency})`} value={line.consumables_cost_per_run} onChange={consumables_cost_per_run => patch({ consumables_cost_per_run })} /><DecimalField label={`Outside service / run (${plan.currency})`} value={line.outside_cost_per_run} onChange={outside_cost_per_run => patch({ outside_cost_per_run })} /></div>
        <h4 className="fq-form-heading">Run recipe</h4><RecipeEditor recipe={line.recipe} onChange={recipe => patch({ recipe })} /><EvidenceEditor value={line.evidence} onChange={evidence => patch({ evidence })} />
      </Card>;
    })}
  </Section>;
}

function OfferEditor({ offer, onChange }: { offer: SupplierOffer; onChange: (offer: SupplierOffer) => void }) {
  const patch = (value: Partial<SupplierOffer>) => onChange(changed(offer, value));
  return <div className="fq-offer"><h4>Applicable supplier offer</h4><div className="fq-grid fq-grid-3"><TextField label="Supplier" value={offer.supplier} onChange={supplier => patch({ supplier })} /><TextField label="Offer manufacturer" value={offer.manufacturer} onChange={manufacturer => patch({ manufacturer })} /><TextField label="Offer manufacturer part number" value={offer.mpn} onChange={mpn => patch({ mpn })} /><SelectField label="Offer currency" value={offer.currency} onChange={currency => patch({ currency })} options={currencies} /><DecimalField label="Each units per price" value={offer.price_unit_quantity} onChange={price_unit_quantity => patch({ price_unit_quantity: price_unit_quantity ?? '' })} hint="Example: price per 100 pieces uses 100." /><IntegerField label="Pack quantity (each)" value={offer.pack_quantity} onChange={pack_quantity => patch({ pack_quantity })} /><IntegerField label="Minimum order (each)" value={offer.minimum_order_quantity} onChange={minimum_order_quantity => patch({ minimum_order_quantity })} /><IntegerField label="Order multiple (each)" value={offer.order_multiple} onChange={order_multiple => patch({ order_multiple })} /><DecimalField label="Freight for this offer" value={offer.freight} onChange={freight => patch({ freight })} /><TextField label="Quoted on" type="date" value={offer.quoted_on} onChange={quoted_on => patch({ quoted_on: quoted_on || null })} /><TextField label="Valid until" type="date" value={offer.valid_until} onChange={valid_until => patch({ valid_until: valid_until || null })} /><IntegerField label="Maximum price age (days)" value={offer.max_age_days} onChange={max_age_days => patch({ max_age_days })} /></div>
    <div className="fq-subheading"><h4>Quantity price breaks</h4><AddButton onClick={() => patch({ price_breaks: [...offer.price_breaks, { minimum_quantity: '1', price: '' }] })}>Add price break</AddButton></div>{!offer.price_breaks.length && <Empty>No price supplied yet. Enter prices from an applicable offer.</Empty>}{offer.price_breaks.map((tier, i) => <div key={i} className="fq-row"><DecimalField label="Minimum purchase quantity (each)" value={tier.minimum_quantity} onChange={minimum_quantity => patch({ price_breaks: replace(offer.price_breaks, i, { ...tier, minimum_quantity: minimum_quantity ?? '' }) })} /><DecimalField label={`Price per ${offer.price_unit_quantity || '?'} each (${offer.currency})`} value={tier.price} onChange={price => patch({ price_breaks: replace(offer.price_breaks, i, { ...tier, price: price ?? '' }) })} /><RemoveButton label={`Remove price break ${i + 1}`} onClick={() => patch({ price_breaks: without(offer.price_breaks, i) })} /></div>)}<Toggle label="This offer applies to this item, account and purchase" checked={offer.applicable} onChange={applicable => patch({ applicable })} /><EvidenceEditor value={offer.evidence} onChange={evidence => patch({ evidence })} />
  </div>;
}

export function HardwareEditor({ plan, onChange }: Props) {
  return <Section title="Purchased hardware" description="Match exact manufacturer part numbers. Price breaks, packs, stock and freight are calculated separately from installation labor." action={<AddButton disabled={!plan.parts.length} onClick={() => onChange({ ...plan, hardware: [...plan.hardware, { id: newId('hardware'), part_id: plan.parts[0].id, manufacturer: '', mpn: '', quantity_per_part: '1', stock_available: 0, stock_unit_value: null, offer: null, evidence: newEvidence() }] })}>Add hardware</AddButton>}>
    {!plan.hardware.length && <Empty>Add BOM hardware and applicable supplier pricing. Add insertion or fastening as a process operation.</Empty>}
    {plan.hardware.map((line, index) => {
      const patch = (value: Partial<HardwareLine>) => onChange({ ...plan, hardware: replace(plan.hardware, index, changed(line, value)) });
      return <Card key={line.id} title={line.mpn || 'Hardware item'} index={index} onRemove={() => onChange({ ...plan, hardware: without(plan.hardware, index) })}><div className="fq-grid fq-grid-3"><PartField parts={plan.parts} value={line.part_id} onChange={part_id => patch({ part_id })} /><TextField label="Manufacturer" value={line.manufacturer} onChange={manufacturer => patch({ manufacturer })} /><TextField label="Manufacturer part number" value={line.mpn} onChange={mpn => patch({ mpn })} /><DecimalField label="Required each per part" value={line.quantity_per_part} onChange={quantity_per_part => patch({ quantity_per_part: quantity_per_part ?? '' })} /><IntegerField label="Stock available (each)" value={line.stock_available} onChange={stock_available => patch({ stock_available })} /><DecimalField label={`Stock value / each (${plan.currency})`} value={line.stock_unit_value} onChange={stock_unit_value => patch({ stock_unit_value })} /></div><EvidenceEditor value={line.evidence} onChange={evidence => patch({ evidence })} />
        {line.offer ? <><OfferEditor offer={line.offer} onChange={offer => patch({ offer })} /><button type="button" className="fq-text-button" onClick={() => patch({ offer: null })}>Remove supplier offer</button></> : <AddButton onClick={() => patch({ offer: { id: newId('offer'), manufacturer: line.manufacturer, mpn: line.mpn, supplier: '', currency: plan.currency, price_unit_quantity: '1', price_breaks: [], pack_quantity: 1, minimum_order_quantity: 1, order_multiple: 1, quoted_on: null, valid_until: null, max_age_days: 30, applicable: false, freight: null, evidence: newEvidence() } })}>Attach supplier offer</AddButton>}
      </Card>;
    })}
  </Section>;
}
