import React, { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import api from '../services/api';
import {
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  CheckCircleIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
} from '@heroicons/react/24/outline';

interface ImportResult {
  total_rows: number;
  created_count: number;
  skipped_count: number;
  errors: Array<{ row: number; reason: string; identifier?: string; employee_id?: string; email?: string }>;
}

const templates: Record<string, { label: string; filename: string; rows: string[][]; href?: string; notes: string[]; directImport?: boolean }> = {
  employees: {
    label: 'Employees / Users',
    filename: 'employees_template.csv',
    rows: [
      ['employee_id', 'first_name', 'last_name', 'department', 'role', 'email', 'password'],
      ['0001', 'John', 'Smith', 'Shop', 'operator', '', ''],
      ['0002', 'Jane', 'Doe', 'Quality', 'quality', 'jane.doe@example.com', 'TempPassword123'],
    ],
    href: '/users',
    notes: ['Uploads directly here.', 'Operators can omit email and password.', 'Non-operators need a row password or default password.'],
    directImport: true,
  },
  parts: {
    label: 'Parts',
    filename: 'parts_template.csv',
    rows: [
      ['part_number', 'name', 'revision', 'part_type', 'unit_of_measure', 'drawing_number', 'customer_name'],
      ['10001', 'Bracket', 'A', 'manufactured', 'each', '10001', ''],
    ],
    href: '/parts',
    notes: ['Uploads directly here.', 'BOM component parts can be loaded here but stay hidden under assemblies in Parts and Routing.'],
    directImport: true,
  },
  boms: {
    label: 'Bill of Materials',
    filename: 'bom_template.csv',
    rows: [
      ['assembly_part_number', 'item_number', 'component_part_number', 'quantity', 'line_type', 'item_type'],
      ['98748', '10', '-10', '1', 'component', 'make'],
    ],
    href: '/bom',
    notes: ['Use the BOM page import flow for now.', 'Component parts stay under the assembly tree, not as routing targets.'],
  },
  customers: {
    label: 'Customers',
    filename: 'customers_template.csv',
    rows: [
      ['code', 'name', 'contact_name', 'email', 'phone', 'payment_terms'],
      ['ACME', 'ACME Manufacturing', 'Sam Buyer', 'sam@example.com', '555-0100', 'Net 30'],
    ],
    href: '/customers',
    notes: ['Uploads directly here.', 'Customer code is optional and can be generated by the system.'],
    directImport: true,
  },
  vendors: {
    label: 'Vendors',
    filename: 'vendors_template.csv',
    rows: [
      ['code', 'name', 'contact_name', 'email', 'phone', 'lead_time_days', 'is_approved'],
      ['SUP-001', 'Steel Supplier', 'Alex Supply', 'alex@example.com', '555-0110', '14', 'true'],
    ],
    href: '/purchasing',
    notes: ['Uploads directly here.', 'Vendor code must be unique. Approval can be true or false.'],
    directImport: true,
  },
  inventory: {
    label: 'Inventory',
    filename: 'inventory_template.csv',
    rows: [
      ['part_number', 'warehouse', 'location', 'quantity_on_hand', 'lot_number', 'unit_cost'],
      ['10001', 'MAIN', 'A-01-01', '25', 'LOT-001', '12.50'],
    ],
    href: '/warehouse?tab=inventory',
    notes: ['Use after parts are loaded.', 'Inventory adjustments should preserve lot/traceability data.'],
  },
  work_centers: {
    label: 'Work Centers',
    filename: 'work_centers_template.csv',
    rows: [
      ['code', 'name', 'work_center_type', 'hourly_rate', 'capacity_hours_per_day', 'area'],
      ['LAS-01', 'Fiber Laser', 'laser', '125', '8', 'Fabrication'],
    ],
    href: '/work-centers',
    notes: ['Uploads directly here.', 'Use work center type names configured in Admin Settings.'],
    directImport: true,
  },
};

function toCsv(rows: string[][]) {
  return rows
    .map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n');
}

function downloadTemplate(key: string) {
  const template = templates[key];
  const blob = new Blob([toCsv(template.rows)], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = template.filename;
  link.click();
  URL.revokeObjectURL(url);
}

function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cell = '';
  let inQuotes = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (char === '"' && inQuotes && next === '"') {
      cell += '"';
      index += 1;
      continue;
    }
    if (char === '"') {
      inQuotes = !inQuotes;
      continue;
    }
    if (char === ',' && !inQuotes) {
      row.push(cell.trim());
      cell = '';
      continue;
    }
    if ((char === '\n' || char === '\r') && !inQuotes) {
      if (char === '\r' && next === '\n') index += 1;
      row.push(cell.trim());
      if (row.some(Boolean)) rows.push(row);
      row = [];
      cell = '';
      continue;
    }
    cell += char;
  }

  row.push(cell.trim());
  if (row.some(Boolean)) rows.push(row);
  return rows;
}

function normalizeHeader(value: string) {
  return value.trim().toLowerCase().replace(/[\s-]+/g, '_').replace(/[^a-z0-9_]/g, '');
}

function rowsToObjects(rows: string[][]) {
  const [headersRaw, ...dataRows] = rows;
  if (!headersRaw?.length) return [];
  const headers = headersRaw.map(normalizeHeader);
  return dataRows
    .map((row, index) => ({
      rowNumber: index + 2,
      data: headers.reduce<Record<string, string>>((acc, header, columnIndex) => {
        if (header) acc[header] = row[columnIndex]?.trim() || '';
        return acc;
      }, {}),
    }))
    .filter(({ data }) => Object.values(data).some(Boolean));
}

function optional(value?: string) {
  const trimmed = (value || '').trim();
  return trimmed || undefined;
}

function asNumber(value?: string, fallback = 0) {
  const trimmed = (value || '').trim();
  if (!trimmed) return fallback;
  const parsed = Number(trimmed);
  if (Number.isNaN(parsed)) throw new Error(`Invalid number "${value}"`);
  return parsed;
}

function asBool(value?: string, fallback = false) {
  const trimmed = (value || '').trim().toLowerCase();
  if (!trimmed) return fallback;
  if (['true', '1', 'yes', 'y', 'active', 'approved'].includes(trimmed)) return true;
  if (['false', '0', 'no', 'n', 'inactive'].includes(trimmed)) return false;
  throw new Error(`Invalid boolean "${value}"`);
}

export default function ImportCenter() {
  const [searchParams, setSearchParams] = useSearchParams();
  const selectedType = searchParams.get('type') || 'employees';
  const selected = templates[selectedType] || templates.employees;
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [defaultPassword, setDefaultPassword] = useState('');
  const [importing, setImporting] = useState(false);
  const [result, setResult] = useState<ImportResult | null>(null);

  const previewRows = useMemo(() => selected.rows.slice(0, 4), [selected]);

  const handleTypeSelect = (key: string) => {
    setSearchParams({ type: key });
    setSelectedFile(null);
    setResult(null);
  };

  const handleCsvImport = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedFile) {
      alert(`Choose a ${selected.label} CSV first.`);
      return;
    }
    setImporting(true);
    try {
      if (selectedType === 'employees') {
        const data = await api.importUsersCsv(selectedFile, defaultPassword);
        setResult({
          total_rows: data.total_rows,
          created_count: data.created_count,
          skipped_count: data.skipped_count,
          errors: data.errors,
        });
        setSelectedFile(null);
        setDefaultPassword('');
        return;
      }

      if (selectedType === 'parts' || selectedType === 'customers' || selectedType === 'vendors' || selectedType === 'work_centers') {
        const data = selectedType === 'parts'
          ? await api.importPartsCsv(selectedFile)
          : selectedType === 'customers'
            ? await api.importCustomersCsv(selectedFile)
            : selectedType === 'vendors'
              ? await api.importVendorsCsv(selectedFile)
              : await api.importWorkCentersCsv(selectedFile);
        setResult({
          total_rows: data.total_rows,
          created_count: data.created_count ?? data.imported_count ?? 0,
          skipped_count: data.skipped_count,
          errors: (data.errors || []).map((error: any) => ({
            row: error.row,
            identifier: error.identifier || error.part_number || error.code || error.name,
            reason: error.reason,
          })),
        });
        setSelectedFile(null);
        return;
      }

      const rows = rowsToObjects(parseCsv(await selectedFile.text()));
      const errors: ImportResult['errors'] = [];
      let createdCount = 0;

      for (const { rowNumber, data } of rows) {
        try {
          if (selectedType === 'parts') {
            await api.createPart({
              part_number: data.part_number,
              name: data.name,
              revision: data.revision || 'A',
              part_type: data.part_type || 'manufactured',
              unit_of_measure: data.unit_of_measure || data.uom || 'each',
              standard_cost: asNumber(data.standard_cost),
              is_critical: asBool(data.is_critical),
              requires_inspection: asBool(data.requires_inspection, true),
              customer_name: optional(data.customer_name),
              customer_part_number: optional(data.customer_part_number),
              drawing_number: optional(data.drawing_number),
              description: optional(data.description),
            });
          } else if (selectedType === 'customers') {
            await api.createCustomer({
              code: optional(data.code),
              name: data.name,
              contact_name: optional(data.contact_name),
              email: optional(data.email),
              phone: optional(data.phone),
              payment_terms: data.payment_terms || 'Net 30',
              address_line1: optional(data.address_line1),
              city: optional(data.city),
              state: optional(data.state),
              zip_code: optional(data.zip_code || data.zip),
              country: data.country || 'USA',
            });
          } else if (selectedType === 'vendors') {
            await api.createVendor({
              code: data.code,
              name: data.name,
              contact_name: optional(data.contact_name),
              email: optional(data.email),
              phone: optional(data.phone),
              payment_terms: optional(data.payment_terms),
              lead_time_days: asNumber(data.lead_time_days, 14),
              is_approved: asBool(data.is_approved),
            });
          } else if (selectedType === 'work_centers') {
            await api.createWorkCenter({
              code: data.code,
              name: data.name,
              work_center_type: data.work_center_type || 'fabrication',
              hourly_rate: asNumber(data.hourly_rate),
              capacity_hours_per_day: asNumber(data.capacity_hours_per_day, 8),
              area: optional(data.area),
              building: optional(data.building),
              description: optional(data.description),
            } as any);
          } else {
            throw new Error('Direct import is not available for this template.');
          }
          createdCount += 1;
        } catch (err: any) {
          errors.push({
            row: rowNumber,
            identifier: data.part_number || data.code || data.name || data.employee_id,
            reason: err.response?.data?.detail || err.message || 'Import failed',
          });
        }
      }

      setResult({
        total_rows: rows.length,
        created_count: createdCount,
        skipped_count: errors.length,
        errors,
      });
      setSelectedFile(null);
      setDefaultPassword('');
    } catch (err: any) {
      alert(err.response?.data?.detail || 'Failed to import CSV');
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Import Center</h1>
        <p className="text-slate-400 mt-1">Start master data cleanly with templates, validation guidance, and routed import actions.</p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-4 gap-6">
        <div className="xl:col-span-1 bg-[#151b28] border border-slate-700 rounded-lg p-3 space-y-2">
          {Object.entries(templates).map(([key, template]) => (
            <button
              key={key}
              onClick={() => handleTypeSelect(key)}
              className={`w-full text-left rounded-lg px-3 py-3 transition-colors ${
                key === selectedType ? 'bg-cyan-500/15 border border-cyan-500/40 text-white' : 'border border-transparent hover:bg-slate-800 text-slate-300'
              }`}
            >
              <div className="font-medium">{template.label}</div>
              <div className="text-xs text-slate-500 mt-1">{template.filename}</div>
            </button>
          ))}
        </div>

        <div className="xl:col-span-3 space-y-5">
          <div className="bg-[#151b28] border border-slate-700 rounded-lg p-5">
            <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
              <div>
                <div className="flex items-center gap-2">
                  <DocumentTextIcon className="h-6 w-6 text-cyan-300" />
                  <h2 className="text-xl font-semibold text-white">{selected.label}</h2>
                </div>
                <ul className="mt-3 space-y-1 text-sm text-slate-400">
                  {selected.notes.map((note) => <li key={note}>{note}</li>)}
                </ul>
              </div>
              <div className="flex flex-wrap gap-2">
                <button onClick={() => downloadTemplate(selectedType)} className="btn-secondary flex items-center">
                  <ArrowDownTrayIcon className="h-5 w-5 mr-2" />
                  Template
                </button>
                {selected.href && <Link to={selected.href} className="btn-secondary">Open Page</Link>}
              </div>
            </div>

            <div className="mt-5 overflow-x-auto border border-slate-700 rounded-lg">
              <table className="min-w-full text-sm">
                <tbody>
                  {previewRows.map((row, rowIndex) => (
                    <tr key={rowIndex} className={rowIndex === 0 ? 'bg-slate-800 text-slate-300' : 'border-t border-slate-700 text-slate-400'}>
                      {row.map((cell, cellIndex) => (
                        <td key={cellIndex} className="px-3 py-2 whitespace-nowrap">{cell || '-'}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {selected.directImport ? (
            <form onSubmit={handleCsvImport} className="bg-[#151b28] border border-slate-700 rounded-lg p-5 space-y-4">
              <div className="flex items-center gap-2">
                <ArrowUpTrayIcon className="h-5 w-5 text-cyan-300" />
                <h3 className="font-semibold text-white">Upload {selected.label} Now</h3>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="label">CSV File</label>
                  <input type="file" accept=".csv,text/csv" className="input" onChange={(e) => setSelectedFile(e.target.files?.[0] || null)} />
                </div>
                {selectedType === 'employees' && (
                <div>
                  <label className="label">Default Password</label>
                  <input
                    type="password"
                    className="input"
                    value={defaultPassword}
                    onChange={(e) => setDefaultPassword(e.target.value)}
                    placeholder="Required for non-operator rows without a password"
                  />
                </div>
                )}
              </div>
              <button type="submit" className="btn-primary flex items-center" disabled={importing || !selectedFile}>
                <ArrowUpTrayIcon className="h-5 w-5 mr-2" />
                {importing ? 'Importing...' : `Import ${selected.label}`}
              </button>
            </form>
          ) : (
            <div className="bg-slate-900/50 border border-slate-700 rounded-lg p-4 text-sm text-slate-400">
              This template uses a specialized workflow. Use the linked module page for document review, commit, or inventory movement tools.
            </div>
          )}

          {result && (
            <div className="bg-[#151b28] border border-slate-700 rounded-lg p-5">
              <div className="flex flex-wrap items-center gap-4">
                <span className="text-slate-300">Rows: {result.total_rows}</span>
                <span className="text-emerald-300 flex items-center gap-1"><CheckCircleIcon className="h-4 w-4" /> Created: {result.created_count}</span>
                <span className="text-amber-300 flex items-center gap-1"><ExclamationTriangleIcon className="h-4 w-4" /> Skipped: {result.skipped_count}</span>
              </div>
              {result.errors.length > 0 && (
                <div className="mt-4 space-y-1 text-sm text-slate-300 max-h-52 overflow-auto">
                  {result.errors.map((error, index) => (
                    <div key={`${error.row}-${index}`}>Row {error.row}{error.identifier ? ` (${error.identifier})` : ''}: {error.reason}</div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
