import { Button } from '../components/ui/Button';
import React, { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import api from '../services/api';
import { ImportTemplateSummary } from '../types/importKit';
import RecoverableImport, { saveImportDownload } from '../components/imports/RecoverableImport';
import { useAuth } from '../context/AuthContext';
interface ImportTypeConfig {
  label: string;
  /** Server template entity key (GET /import/templates/{entity}); null = no server template. */
  entity: string | null;
  href?: string;
  notes: string[];
  /** Direct = preview/commit upload lives on this page. Linked = use the module page. */
  mode: 'direct' | 'linked';
}

const importTypes: Record<string, ImportTypeConfig> = {
  employees: {
    label: 'Employees / Users',
    entity: 'users',
    href: '/users',
    mode: 'direct',
    notes: [
      'Uploads directly here.',
      'Operators can omit email and password.',
      'Non-operators need a row password or default password.',
    ],
  },
  parts: {
    label: 'Parts',
    entity: 'parts',
    href: '/parts',
    mode: 'direct',
    notes: [
      'Uploads directly here.',
      'BOM component parts can be loaded here but stay hidden under assemblies in Parts and Routing.',
    ],
  },
  materials: {
    label: 'Materials & Supplies',
    entity: 'materials',
    href: '/materials',
    mode: 'direct',
    notes: ['Uploads directly here.', 'Raw material, hardware, and consumable part masters for purchasing.'],
  },
  boms: {
    label: 'Bill of Materials',
    entity: 'bom',
    href: '/bom',
    mode: 'linked',
    notes: [
      'Use the BOM page import wizard to review the column mapping before committing.',
      'Component parts stay under the assembly tree, not as routing targets.',
    ],
  },
  routings: {
    label: 'Routings',
    entity: 'routings',
    href: '/routing',
    mode: 'linked',
    notes: [
      'Use the Routing page "Import Routings" wizard to dry-run before committing.',
      'Operation rows are grouped into one draft routing per part + revision.',
      'Parts and work centers must already exist; a new revision is created if one is present.',
    ],
  },
  customers: {
    label: 'Customers',
    entity: 'customers',
    href: '/customers',
    mode: 'direct',
    notes: ['Uploads directly here.', 'Customer code is optional and can be generated by the system.'],
  },
  vendors: {
    label: 'Vendors',
    entity: 'vendors',
    href: '/purchasing',
    mode: 'direct',
    notes: ['Uploads directly here.', 'Vendor code must be unique. Approval can be true or false.'],
  },
  work_centers: {
    label: 'Work Centers',
    entity: 'work-centers',
    href: '/work-centers',
    mode: 'direct',
    notes: ['Uploads directly here.', 'Use work center type names configured in Admin Settings.'],
  },
  work_orders: {
    label: 'Open Work Orders',
    entity: 'work-orders',
    href: '/work-orders',
    mode: 'direct',
    notes: [
      'Imports in-flight jobs from your legacy schedule.',
      'Operations up to completed_through_seq are marked complete as paper-history; the next operation becomes ready on the floor.',
      'Parts must already exist with a released routing. Past due dates are allowed — open jobs can be overdue.',
    ],
  },
  purchase_orders: {
    label: 'Open Purchase Orders',
    entity: 'purchase-orders',
    href: '/purchasing',
    mode: 'direct',
    notes: [
      'Imports open (issued, not yet received) purchase orders.',
      'Rows sharing a po_number become lines of one PO; a blank po_number gets a generated number.',
      'Vendors and parts must already exist. POs land in issued status so receiving can act on them.',
    ],
  },
  inventory: {
    label: 'Inventory',
    entity: null,
    href: '/warehouse?tab=inventory',
    mode: 'linked',
    notes: ['Use after parts are loaded.', 'Inventory adjustments should preserve lot/traceability data.'],
  },
};

export default function ImportCenter() {
  const [params, setParams] = useSearchParams();
  const key = params.get('type') || 'employees';
  const selectedKey = importTypes[key] ? key : 'employees';
  const selected = importTypes[selectedKey];
  const { user } = useAuth();
  const [templates, setTemplates] = useState<ImportTemplateSummary[]>([]);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => {
    let active = true;
    api
      .getImportTemplates()
      .then(data => {
        if (active) setTemplates(data.templates || []);
      })
      .catch(() => {});
    return () => {
      active = false;
    };
  }, []);
  const isAdmin = user?.is_superuser || ['admin', 'platform_admin'].includes(user?.role || '');
  const roles =
    selected.entity === 'users'
      ? ['admin']
      : ['parts', 'materials', 'work-orders'].includes(selected.entity || '')
        ? ['admin', 'manager', 'supervisor']
        : ['admin', 'manager'];
  const canImport = !!isAdmin || roles.includes(user?.role || '');
  const template = templates.find(item => item.entity === selected.entity);
  const download = async () => {
    if (!selected.entity) return;
    setDownloading(true);
    setError('');
    try {
      const { blob, filename } = await api.downloadImportTemplate(selected.entity);
      saveImportDownload(blob, filename);
    } catch {
      setError('Template download failed. Try again.');
    } finally {
      setDownloading(false);
    }
  };
  return (
    <div className="space-y-5">
      <h1 className="text-2xl font-semibold">Import Center</h1>
      <p className="text-fd-mute">
        Review spreadsheet data, import approved rows, and return to saved receipts to resolve the rest.
      </p>
      <nav aria-label="Import record types" className="flex flex-wrap gap-2">
        {Object.entries(importTypes).map(([id, config]) => (
          <Button
            key={id}
            variant={id === selectedKey ? 'primary' : 'secondary'}
            aria-current={id === selectedKey ? 'page' : undefined}
            onClick={() => setParams({ type: id })}
          >
            {config.label}
          </Button>
        ))}
      </nav>
      <section className="card space-y-3">
        <h2 className="text-xl font-semibold">{selected.label}</h2>
        <ul className="list-disc pl-5">
          {selected.notes.map(note => (
            <li key={note}>{note}</li>
          ))}
        </ul>
        {selected.entity && (
          <Button variant="secondary" onClick={download} disabled={downloading}>
            {downloading ? 'Downloading…' : 'Download template (.xlsx)'}
          </Button>
        )}
        {template && <p className="text-sm text-fd-mute">Columns: {template.columns.join(', ')}</p>}
        {selected.mode === 'linked' && selected.href && (
          <Link className="text-fd-blue underline" to={selected.href}>
            Open {selected.label}
          </Link>
        )}
        {error && <p role="alert">{error}</p>}
      </section>
      {selected.mode === 'direct' && selected.entity && (
        <RecoverableImport key={selected.entity} entity={selected.entity} canImport={canImport} />
      )}
    </div>
  );
}
