from fastapi import APIRouter
from app.api.endpoints import auth, work_centers, parts, work_orders, shop_floor, bom, routing, mrp, custom_fields, quality, inventory, purchasing, scheduling, documents, reports, shipping, quotes, users, customers, calibration, scanner, traceability, audit, quote_calculator, dxf_parser, admin_settings, receiving, po_upload, analytics, errors, search, exports, print_reports, rfq_quotes

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["Authentication"])
api_router.include_router(work_centers.router, prefix="/work-centers", tags=["Work Centers"])
api_router.include_router(parts.router, prefix="/parts", tags=["Parts"])
api_router.include_router(bom.router, prefix="/bom", tags=["Bill of Materials"])
api_router.include_router(routing.router, prefix="/routing", tags=["Routing"])
api_router.include_router(inventory.router, prefix="/inventory", tags=["Inventory"])
api_router.include_router(mrp.router, prefix="/mrp", tags=["Material Requirements Planning"])
api_router.include_router(quality.router, prefix="/quality", tags=["Quality Management"])
api_router.include_router(custom_fields.router, prefix="/custom-fields", tags=["Custom Fields"])
api_router.include_router(work_orders.router, prefix="/work-orders", tags=["Work Orders"])
api_router.include_router(shop_floor.router, prefix="/shop-floor", tags=["Shop Floor"])
api_router.include_router(purchasing.router, prefix="/purchasing", tags=["Purchasing"])
api_router.include_router(scheduling.router, prefix="/scheduling", tags=["Scheduling"])
api_router.include_router(documents.router, prefix="/documents", tags=["Documents"])
api_router.include_router(reports.router, prefix="/reports", tags=["Reports"])
api_router.include_router(shipping.router, prefix="/shipping", tags=["Shipping"])
api_router.include_router(quotes.router, prefix="/quotes", tags=["Quotes"])
api_router.include_router(users.router, prefix="/users", tags=["Users"])
api_router.include_router(customers.router, prefix="/customers", tags=["Customers"])
api_router.include_router(calibration.router, prefix="/calibration", tags=["Calibration"])
api_router.include_router(scanner.router, prefix="/scanner", tags=["Scanner"])
api_router.include_router(traceability.router, prefix="/traceability", tags=["Traceability"])
api_router.include_router(audit.router, prefix="/audit", tags=["Audit"])
api_router.include_router(quote_calculator.router, prefix="/quote-calc", tags=["Quote Calculator"])
api_router.include_router(dxf_parser.router, prefix="/dxf-parser", tags=["DXF Parser"])
api_router.include_router(rfq_quotes.router, prefix="/rfq-packages", tags=["AI RFQ Quotes"])
api_router.include_router(admin_settings.router, prefix="/admin/settings", tags=["Admin Settings"])
api_router.include_router(receiving.router, prefix="/receiving", tags=["Receiving & Inspection"])
api_router.include_router(po_upload.router, prefix="/po-upload", tags=["PO Upload"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["Analytics & BI"])
api_router.include_router(search.router, prefix="/search", tags=["Global Search"])
api_router.include_router(exports.router, prefix="/exports", tags=["Data Export"])
api_router.include_router(print_reports.router, prefix="/print", tags=["Print Reports"])
api_router.include_router(errors.router, tags=["Error Logging"])
