import { test, expect, TEST_USERS } from './fixtures';

test('cycle count survives reload, reviews stock and posts exactly once from mobile', async ({ adminPage: page, request }, testInfo) => {
  const api = process.env.E2E_API_URL || 'http://127.0.0.1:8000/api/v1';
  const login = await request.post(`${api}/auth/login`, { form: { username: TEST_USERS.admin.email, password: TEST_USERS.admin.secret } });
  expect(login.ok()).toBeTruthy();
  const headers = { Authorization: `Bearer ${(await login.json()).access_token}`, 'X-Requested-With': 'XMLHttpRequest' };
  const stamp = `COUNT-${Date.now()}`;
  const part = await request.post(`${api}/materials/`, { headers, data: { part_number: stamp, name: 'Synthetic cycle-count acceptance stock', part_type: 'purchased', unit_of_measure: 'each' } });
  expect(part.ok(), await part.text()).toBeTruthy();
  const partId = (await part.json()).id;
  const location = await request.post(`${api}/inventory/locations`, { headers, data: { code: stamp, name: 'Acceptance rack', warehouse: 'COUNT-E2E' } });
  expect(location.ok(), await location.text()).toBeTruthy();
  const received = await request.post(`${api}/inventory/receive`, { headers, data: { part_id: partId, quantity: 24, location_code: stamp, lot_number: 'HEAT-E2E', unit_cost: 12.5 } });
  expect(received.ok(), await received.text()).toBeTruthy();
  await page.goto('/warehouse?tab=inventory&inventory_tab=counts');
  await page.getByRole('button', { name: 'Schedule count', exact: true }).click();
  const create = page.getByRole('dialog', { name: 'Schedule cycle count' });
  await create.getByLabel(/^Location/).selectOption(stamp);
  await create.getByLabel('Instructions', { exact: true }).fill('Count all plate blanks on this rack.');
  await create.getByRole('button', { name: 'Create count', exact: true }).click();
  await page.getByRole('button', { name: 'Start counting', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Review adjustments', exact: true })).toBeDisabled();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Count', exact: true }).filter({ visible: true }).click();
  const entry = page.getByRole('dialog', { name: `Count ${stamp}` });
  await entry.getByLabel(/^Quantity counted/).fill('23');
  await entry.getByLabel('Count notes', { exact: true }).fill('One plate short on physical count.');
  await expect(entry).toHaveCSS('opacity', '1');
  await page.screenshot({ path: testInfo.outputPath('cycle-count-mobile.png'), animations: 'disabled' });
  await entry.getByRole('button', { name: 'Save count', exact: true }).click();
  await expect(entry).toHaveCount(0);
  await page.reload();
  await expect(page.getByText('Counted 23', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Review adjustments', exact: true }).click();
  const review = page.getByRole('dialog', { name: 'Review cycle count adjustments' });
  const post = review.getByRole('button', { name: 'Post adjustments & complete', exact: true });
  await expect(post).toBeDisabled();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await expect(review).toHaveCSS('opacity', '1');
  await page.screenshot({ path: testInfo.outputPath('cycle-count-review-desktop.png'), animations: 'disabled' });
  await review.getByRole('checkbox').check();
  await post.click();
  await expect(review).toHaveCount(0);
  await expect(page.getByText(/1 stock rows adjusted\./)).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Review adjustments', exact: true })).toHaveCount(0);
  const ledger = await request.get(`${api}/inventory/transactions`, { headers, params: { part_id: partId, transaction_type: 'count' } });
  const rows = await ledger.json();
  expect(rows).toHaveLength(1);
  expect(rows[0].quantity).toBe(-1);
});
